### ISSUE TITLE
pip installation does not work with Python 3

### ISSUE THREAD

**Issue by svenhafeneger** [ibm-cds-labs/ibmos2spark#9]
I tried to install `ibmos2spark` for Python 3 on my local setup and on IBM DSX.
In both cases I get the following message:
```
Collecting ibmos2spark
  Using cached ibmos2spark-0.0.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/s4e6-b19de969a9b6ab-3e1941541687/pip-build/ibmos2spark/setup.py", line 24, in <module>
        from ibmos2spark.__info__ import __version__
      File "/tmp/s4e6-b19de969a9b6ab-3e1941541687/pip-build/ibmos2spark/ibmos2spark/__init__.py", line 19, in <module>
        from osconfig import softlayer, bluemix, softlayer2d, bluemix2d
    ImportError: No module named 'osconfig'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/s4e6-b19de969a9b6ab-3e1941541687/pip-build/ibmos2spark/
```

The module `osconfig` cannot be found during installation. The `osconfig.py` file is in the same folder as the `__init__.py` file. 

I think in `__init_.py` the line `from osconfig import softlayer, bluemix, softlayer2d, bluemix2d` needs to be adapted to it is valid for both Python 2 and 3 import mechanisms.

**Comment by bassel-zeidan** [comment]
This has been solved with the latest updates. Closing this item...
fyi @gadamc

**Comment by bassel-zeidan** [comment]
The latest updates can be picked up under version `0.0.8` of the lib
